from django.urls import path
from . views import *

urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('galeria/', galeria, name="galeria"), 
    path('pago/', pago, name="pago"),
    path('productos/', productos, name="productos"),
    path('clases/', clases, name="clases"),
    path('consultar_historial/', consultar_historial, name='consultar_historial'),
    path('agregar-producto/', agregar_productos, name="agregar_producto"),
    path('listar-producto/', listar_productos, name="listar_producto"),
    path('modificar-producto/<id>/', modificar_producto, name = "modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name = "eliminar_producto"),
    path('agregar-alumnos/',agregar_alumno,name = "agregar_alumno"),
    path('listar-alumno/',listar_alumnos, name = "listar_alumnos"),
    path('modificar-alumno/<rut>/',modificar_alumno,name = "modificar_alumno"),
    path('eliminar-alumno/<rut>/',eliminar_alumno,name="eliminar_alumno"),
    path('listar-consultas/', listar_consultas, name="listar_consultas"),
    path('ver_consulta/<id>/', ver_consulta, name='ver_consulta'),
    path('responder_consulta/<id>/', responder_consulta, name='responder_consulta'),
    path('eliminar-consulta/<id>/', eliminar_consulta, name="eliminar_consulta"),
    path('agregar-profesor/',agregar_profesor,name = "agregar_profesor"),
    path('listar-profesor/',listar_profesor, name = "listar_profesor"),
    path('eliminar-profesor/<rut>/',eliminar_profesor,name="eliminar_profesor"),
    path('modificar-profesor/<rut>/',modificar_profesor,name = "modificar_profesor"),
    path('agregar-clases/', agregar_clases, name="agregar_clases"),
    path('listar-clases/', listar_clases, name="listar_clases"),
    path('modificar-clases/<id>/', modificar_clase, name = "modificar_clases"),
    path('eliminar-clases/<id>/', eliminar_clase, name = "eliminar_clases"),
    path('listar-pagos/', listar_pagos, name="listar_pagos"),
    path('agregar-pagos/', agregar_pagos, name="agregar_pagos"),
    path('modificar-pagos/<id>/', modificar_pagos, name = "modificar_pagos"),
    path('contact', contact, name="contact"),
    path('informe-total-alumnos/', informe_total_alumnos, name='informe_total_alumnos'),
    path('informe-pagos-mensuales/', informe_pagos_mensuales, name='informe_pagos_mensuales'),
    path('informe-pagos-atrasados/', informe_pagos_atrasados, name='informe_pagos_atrasados'),
    path('seleccionar-informe/', seleccionar_informe, name="seleccionar_informe" ),
    path('generar-informe/', generar_informe, name='generar_informe'),
    path('autocomplete-alumno/', autocomplete_alumno, name='autocomplete-alumno'),
]